### ISSUE TITLE
Duplicate Information

### ISSUE THREAD

**Issue by rabinsahoo** [roll-wg/rpl-observations#4]
"The DEFAULT_DAO_DELAY of 1sec does not help much with aggregation. The upstream parent nodes should wait for more time then the child nodes so as to effectively aggregate.  Can we have
 DEFAULT_DAO_DELAY a function of the level/rank the node is at?"

Above Issue is mentioned in both section 6.1 and and 7.1. It has to be removed from section 7.1

**Comment by nyrahul** [comment]
This is fixed in -02. Thanks.
